// lib/mockData.ts

import type { RacerProfile, RaceRecord } from "@/types";

// ─── MOCK RACERS ──────────────────────────────────────────────────────────────

export const MOCK_RACERS: RacerProfile[] = [
  {
    id:       1,
    name:     "Amr Borkan",
    tag:      "@B7_M3",
    car:      "BMW M4 CSL",
    hp:       543,
    torque:   650,
    country:  "EG",
    verified: "racer",
    topSpeed: 284,
    bestTime: "00:38.42",
    races:    47,
    avatar:   "KM",
    badge:    "gold",
    instagram: "Borkan_m_racing",
    twitter:   "Borkan_m_racing",
  },
  {
    id:       2,
    name:     "Abdo KOSH",
    tag:      "@Abdo_drift",
    car:      "Nissan GT-R R35",
    hp:       600,
    torque:   720,
    country:  "JR",
    verified: "tuner",
    topSpeed: 312,
    bestTime: "00:35.18",
    races:    89,
    avatar:   "YT",
    badge:    "silver",
    instagram: "Abdo_drift_jp",
  },
  {
    id:       3,
    name:     "عريس الجنة",
    tag:      "@عريس الجنة يا برو",
    car:      "Porsche 911 GT3 RS",
    hp:       518,
    torque:   470,
    country:  "🇮🇹",
    verified: "racer",
    topSpeed: 296,
    bestTime: "00:36.55",
    races:    63,
    avatar:   "MF",
    badge:    "gold",
    twitter:  "بدوي_f1_racing",
  },
  {
    id:       4,
    name:     "SAM ",
    tag:      "@sam_mayez",
    car:      "Ford Mustang GTD",
    hp:       999,
    torque:   999,
    country:  "🇦🇪",
    verified: "racer",
    topSpeed: 271,
    bestTime: "00:41.20",
    races:    28,
    avatar:   "AH",
    badge:    "none",
    instagram: "sam_mayez",
  },
  {
    id:       5,
    name:     "EL GYAAR",
    tag:      "@EL GYAAR_speed",
    car:      "Ferrari 488 GTB",
    hp:       660,
    torque:   760,
    country:  "🇫🇷",
    verified: "car",
    topSpeed: 330,
    bestTime: "00:32.88",
    races:    112,
    avatar:   "LB",
    badge:    "platinum",
    youtube:  "EL GYAAR_speed_official",
    instagram: "EL GYAAR_bianchi_racing",
  },
  {
    id:       6,
    name:     "Ryan Storm",
    tag:      "@storm_rx7",
    car:      "Mazda RX-7 FD",
    hp:       480,
    torque:   520,
    country:  "🇺🇸",
    verified: "tuner",
    topSpeed: 265,
    bestTime: "00:44.10",
    races:    35,
    avatar:   "RS",
    badge:    "none",
    twitter:  "storm_rx7",
  },
];

// ─── MOCK RACE HISTORY ────────────────────────────────────────────────────────

export const MOCK_HISTORY: RaceRecord[] = [
  {
    id:       1,
    date:     "May 14, 2026",
    time:     "22:15",
    duration: "00:38.42",
    maxSpeed: 284,
    avgSpeed: 231,
    route:    "Dubai Autodrome",
    mode:     "0-200 km/h",
    unit:     "kmh",
    flagged:  false,
  },
  {
    id:       2,
    date:     "May 12, 2026",
    time:     "19:30",
    duration: "00:41.88",
    maxSpeed: 271,
    avgSpeed: 218,
    route:    "Desert Straight",
    mode:     "Quarter Mile",
    unit:     "kmh",
    flagged:  false,
  },
  {
    id:       3,
    date:     "May 10, 2026",
    time:     "20:45",
    duration: "00:44.20",
    maxSpeed: 256,
    avgSpeed: 209,
    route:    "Custom Run",
    mode:     "Top Speed",
    unit:     "kmh",
    flagged:  true,
  },
  {
    id:       4,
    date:     "May 8, 2026",
    time:     "21:00",
    duration: "00:36.90",
    maxSpeed: 291,
    avgSpeed: 244,
    route:    "Highway Straight",
    mode:     "0-100 km/h",
    unit:     "kmh",
    flagged:  false,
  },
];

// ─── MOCK ROUTE POINTS (for replaying a saved race on the map) ────────────────

/**
 * A static set of SVG-space route points used for history replay
 * and the admin panel map preview.
 */
export const MOCK_REPLAY_ROUTE = [
  { x: 40,  y: 260 },
  { x: 80,  y: 240 },
  { x: 120, y: 215 },
  { x: 165, y: 190 },
  { x: 210, y: 162 },
  { x: 255, y: 135 },
  { x: 300, y: 110 },
  { x: 345, y:  85 },
  { x: 375, y:  62 },
];